server:
  port: 8083

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: qudratjonkomilov
    url: jdbc:postgresql://postgres:5433/gym
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: api-gateway
  zipkin:
    base-url: http://zipkin:9411
  cloud:
    gateway:
      routes:
        - id: fitness
          uri: lb://FITNESS
          predicates:
            - Path=/fitness/**

        - id: workload
          uri: lb://WORKLOAD
          predicates:
            - Path=/workload/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
